<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SA6CFNU6" failures="1" tests="10" name="chromeTest" time="178.211" errors="0" timestamp="2024-08-25T20:30:58 IST">
  <testcase classname="TestCases.TC1_Register" name="VerifyRegister" time="6.709"/>
  <testcase classname="TestCases.TC2_Login" name="verify_Login" time="3.135"/>
  <testcase classname="TestCases.TC3_loginDDT" name="verify_login_DDT" time="7.343"/>
  <testcase classname="TestCases.TC3_loginDDT" name="verify_login_DDT" time="6.377"/>
  <testcase classname="TestCases.TC3_loginDDT" name="verify_login_DDT" time="12.705"/>
  <testcase classname="TestCases.TC3_loginDDT" name="verify_login_DDT" time="11.933"/>
  <testcase classname="TestCases.TC3_loginDDT" name="verify_login_DDT" time="20.221"/>
  <testcase classname="TestCases.TC3_loginDDT" name="verify_login_DDT" time="14.645">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestCases.TC3_loginDDT.verify_login_DDT(TC3_loginDDT.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- verify_login_DDT -->
  <testcase classname="TestCases.TC4_Checkin_Page" name="orderProduct" time="21.063"/>
  <testcase classname="TestCases.TC5_OrderHistory" name="verifyOrderHistory" time="6.13"/>
</testsuite> <!-- chromeTest -->
